---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service-expose
  namespace: default
  labels:
    app: discovery-service
spec:
  ports:
  - name: discovery-service
    protocol: TCP
    port: 31702
    targetPort: 8761
    nodePort: 31702
  selector:
    app: discovery-service
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  labels:
    app: discovery-service
spec:
  ports:
  - port: 8761
    targetPort: 8761
    name: discovery-service
  clusterIP: None
  selector:
    app: discovery-service
---    
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: discovery-service
spec:
  serviceName: "discovery-service"
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
      - resources:
          requests:
            cpu: 100m
            memory: 192Mi 
        name: discovery-service
        image: mycluster.icp:8500/default/kbastani/discovery-service:latest
        ports:
        - containerPort: 8761
        env:
        - name: JAVA_OPTS
          value: |
            -Xmx160m -Dserver.port=8761
              -Deureka.instance.lease-expiration-duration-in-seconds=60
              -Deureka.server.response-cache-update-interval-ms=5000
              -Deureka.server.evictionIntervalTimerInMs=5000
              -Dspring.profiles.active=cloud
  podManagementPolicy: "Parallel"
